fix glibc build
fixes #10677

src/apk_defines.h:152:15: error: unknown type name 'uint32_t'
 static inline uint32_t get_unaligned32(const void *ptr)
               ^~~~~~~~

(cherry picked from commit a9916c2d4a14a509daf7e3bc73faee3a8134071f)